---
title: "Lab3Practice"
author: "Yangfeng Shi"
date: "9/20/2019"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
```

```{r}
icecream <- read.table("/Users/yangfengshi/Desktop/STA\ 463/Lab2/icecream.txt")
head(icecream)
copier <- read.table("/Users/yangfengshi/Desktop/STA\ 463/Lab2/CH01PR20.txt")
head(copier)
```

```{r}
colnames(copier)=c("minutes","number")

puzzle.summary <- icecream %>% group_by(ice_cream) %>% summarise(Mean=mean(puzzle),
            Variance=var(puzzle))%>%as.data.frame()
```

```{r}
plot(density(copier$minutes),xlab="minutes")#,ylab="density")
```

```{r}
copier.fit <- lm(minutes~number,data=copier)
copier.fit
class(copier.fit)
str(copier.fit)
summary(copier.fit)
```

##Regression line

```{r}
plot(minutes~number, data=copier)
abline(-0.5802,15.0352)#by definition of the line abline(intercept, slope)

#The following are alternative ways to draw the fitted regression line.
lines(copier$number,-0.5802+15.0352*copier$number)#other way

abline(copier.fit)#simple way
```

```{r}
summary(copier.fit)
```

